### ISSUE TITLE
405 when using RestApi behind traefik

### ISSUE THREAD

**Issue by smaktacular** [jon6fingrs/ghostboard#10]
When trying to use the RestApi to post text to my board (which is working fine ❤️)

using
`curl -X POST "https://gb.domain.com" -d "text=example"`

i get `405: Method Not Allowed`

I've set up a traefik instance as a reverse proxy before the container with the following compose. 

```
version: "3.7"

networks:
  backend:
    external:
      name: backend

services:
  app:
    image: thehelpfulidiot/ghostboard-server:nginx
    restart: unless-stopped
    networks:
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=backend
      - traefik.http.routers.ghostboard.entrypoints=websecure
      - "traefik.http.routers.ghostboard.rule=Host(`gb.domain.com`)"
      - traefik.http.routers.ghostboard.tls=true
      - traefik.http.routers.ghostboard.tls.certresolver=leresolver
      - traefik.http.services.ghostboard.loadbalancer.server.port=80
```

I don't see any container logs, which makes me think that the request is somehow mishandled by one of the reverse proxies included, but I have no idea where to look. Does someone have an idea?
