### ISSUE TITLE
difficulty setting up project behind traefik

### ISSUE THREAD

**Issue by jon6fingrs** [jon6fingrs/ghostboard#6]
a reddit user posted that it was difficult for this project to run if traefik is the reverse proxy. i made an image with nginx built in so the redirection can take place at the image level.

please test it by using thehelpfulidiot/ghostboard-server:nginx

should be possible to more easily forward all traffic to port 80. 

let me know if this works and i will add it to repo. thanks!

**Comment by fjordnode** [comment]
ghostboard  | /usr/lib/python3/dist-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
ghostboard  |   self.warnings.warn(
ghostboard  | 2025-02-02 14:04:44,493 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
ghostboard  | 2025-02-02 14:04:44,493 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
ghostboard  | 2025-02-02 14:04:44,495 INFO RPC interface 'supervisor' initialized
ghostboard  | 2025-02-02 14:04:44,495 CRIT Server 'unix_http_server' running without any HTTP authentication checking
ghostboard  | 2025-02-02 14:04:44,495 INFO supervisord started with pid 1
ghostboard  | 2025-02-02 14:04:45,496 INFO spawned: 'nginx' with pid 7
ghostboard  | 2025-02-02 14:04:45,497 INFO spawned: 'python' with pid 8
ghostboard  | 2025-02-02 14:04:46,505 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ghostboard  | 2025-02-02 14:04:46,505 INFO success: python entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by jon6fingrs** [comment]
ok so pull the image again. i just made a small tweak. now when you run it, you should just open port 80. dont open worry about ports 8080 and 8765. then do something like this for your traefik config (this is what works for me):

```
http:
  routers:
    ghostboard:
      rule: "Host(`<ghostboard-domain>`)"
      entryPoints: # my basic traefik config
        - websecure
      tls: # i use cloudflare
        certresolver: cloudflare
      service: ghostboard-service

  services:
    ghostboard-service:
      loadBalancer:
        servers:
          - url: "http://<ghostboard-container-url>:80"
```

does that help?

**Comment by fjordnode** [comment]
> ok so pull the image again. i just made a small tweak. now when you run it, you should just open port 80. dont open worry about ports 8080 and 8765. then do something like this for your traefik config (this is what works for me):
> 
> ```
> http:
>   routers:
>     ghostboard:
>       rule: "Host(`<ghostboard-domain>`)"
>       entryPoints: # my basic traefik config
>         - websecure
>       tls: # i use cloudflare
>         certresolver: cloudflare
>       service: ghostboard-service
> 
>   services:
>     ghostboard-service:
>       loadBalancer:
>         servers:
>           - url: "http://<ghostboard-container-url>:80"
> ```
> 
> does that help?

In my setup traefik has access to the docker socket, so I usually do reverse proxy with labels in compose.
All I really need is the image internal port, which I understand is 80 now.


For now this actually seems to work:
```
version: "3.8"
services:
  ghostboard-server:
    container_name: ghostboard
    image: thehelpfulidiot/ghostboard-server:nginx
    ports:
      - 8086:80
    restart: always
    networks:
      - roci
    labels:
      - traefik.enable=true
      - traefik.docker.network=roci
      - traefik.http.routers.ghostboard-http.rule=Host(`ghostboard.mydomain.com`)
      - traefik.http.services.ghostboard-http.loadbalancer.server.port=80
networks:
  roci:
    external: true
```
